version: '3.9'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ACME_AGREE=false
  gitroom-postgres:
    image: postgres:14.5
    container_name: gitroom-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: gitroom-local-pwd
      POSTGRES_USER: gitroom-local
      POSTGRES_DB: gitroom-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  gitroom-redis:
    image: redis:7.2
    container_name: gitroom-redis
    restart: always
    ports:
      - 6379:6379
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "https://localhost/api"
    container_name: frontend
    restart: always
    ports:
      - 4200:4200
    environment:
      FRONTEND_URL: https://localhost
      NEXT_PUBLIC_BACKEND_URL: https://localhost/api
      BACKEND_INTERNAL_URL: http://192.168.10.178:3000
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        NEXT_PUBLIC_BACKEND_URL: "https://localhost/api"
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    environment:
      FRONTEND_URL: https://localhost
      NEXT_PUBLIC_BACKEND_URL: https://localhost/api
      BACKEND_INTERNAL_URL: http://192.168.10.178:3000
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadminpassword"
      console-address: 9001
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  caddy_data:
  caddy_config:
  minio-data:
  postgres-volume:
    external: false
