# Use the official Node.js image.
# https://hub.docker.com/_/node
FROM node:20-alpine

# Create and change to the app directory.
WORKDIR /usr/src/app


# Copy local code to the container image.
COPY dist/apps/backend /usr/src/app
COPY package.json /usr/src/app
# Install production dependencies.
RUN npm install


# Run the Next.js application.
CMD [ "node", "main.js"]

# Inform Docker that the container is listening on the specified port at runtime.
EXPOSE 4200
